# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: haiyun
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: learning-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: learning-api

stages:
  default:
    params:
      tableNamePrefix: ${self:service}-${sls:stage}
      coursesTableName: ${param:tableNamePrefix}-courses

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  role: arn:aws:iam::017820698732:role/MyLambdaDynamoDBExecutionRole
  environment:
    STAGE: ${sls:stage}
    COURSES_TABLE: ${param:coursesTableName}

package:
  individually: true
  exclude:
    - src/**
    - README.md

functions:
  hello:
    handler: src/hello/hello.handler
    events:
      - httpApi:
          path: /
          method: get
    package:
      include:
        - src/hello/hello.mjs

  addCourse:
    handler: src/courses/addCourse.handler
    events:
      - httpApi:
          path: /courses
          method: post
    package:
      include:
        - src/courses/addCourse.mjs

  getCourseList:
    handler: src/courses/getCourseList.handler
    events:
      - httpApi:
          path: /courses
          method: get
    package:
      include:
        - src/courses/getCourseList.mjs

resources:
  Resources:
    CoursesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:coursesTableName}
