# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: haiyun
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: learning-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: my-node-express-api

stages:
  default:
    params:
      tableName: users-table-${sls:stage}

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  role: arn:aws:iam::017820698732:role/MyLambdaDynamoDBExecutionRole
  environment:
    USERS_TABLE: ${param:tableName}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}
